apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myrole-rolebinding
  namespace: mynamespace 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myrole 
subjects:
- namespace: mynamespace
  kind: ServiceAccount
  name: myportfolioservice