apiVersion: v1
kind: Service
metadata:
  name: myportfolio
  namespace: mynamespace
spec:
  selector:
    app: myportfolio
  ports:
  - protocol: TCP
    port: 80           
    targetPort: 80 
  type: LoadBalancer
